version: '3'

volumes:
  node_modules:

services:
  web-app:
    build:
      context: .
      dockerfile: ./_docker/Dockerfile
    volumes:
      - node_modules:/app/node_modules
    ports:
      - 8080:8080